
# ARGS=trace:qemu_vfree, \
# trace:qemu_anon_ram_free, \
# trace:virtqueue_fill, \
# trace:virtqueue_flush, \
# trace:virtqueue_pop, \
# trace:virtio_queue_notify, \
# trace:virtio_irq, \
# trace:virtio_notify, \
# trace:virtio_set_status, \
# trace:virtio_rng_guest_not_ready, \
# trace:virtio_rng_pushed, \
# trace:virtio_rng_request, \
# trace:virtio_serial_send_control_event, \
# trace:virtio_serial_throttle_port, \
# trace:virtio_serial_handle_control_message, \
# trace:virtio_serial_handle_control_message_port, \
# trace:virtio_console_flush_buf, \
# trace:virtio_console_chr_read, \
# trace:virtio_console_chr_event, \
# trace:bdrv_open_common, \
# trace:bdrv_lock_medium, \
# trace:multiwrite_cb, \
# trace:bdrv_aio_multiwrite, \
# trace:bdrv_aio_discard, \
# trace:bdrv_aio_flush, \
# trace:bdrv_aio_readv, \
# trace:bdrv_aio_writev, \
# trace:bdrv_aio_write_zeroes, \
# trace:bdrv_co_readv, \
# trace:bdrv_co_copy_on_readv, \
# trace:bdrv_co_readv_no_serialising, \
# trace:bdrv_co_writev, \
# trace:bdrv_co_write_zeroes, \
# trace:bdrv_co_io_em, \
# trace:bdrv_co_do_copy_on_readv, \
# trace:stream_one_iteration, \
# trace:stream_start, \
# trace:commit_one_iteration, \
# trace:commit_start, \
# trace:mirror_start, \
# trace:mirror_restart_iter, \
# trace:mirror_before_flush, \
# trace:mirror_before_drain, \
# trace:mirror_before_sleep, \
# trace:mirror_one_iteration, \
# trace:mirror_iteration_done, \
# trace:mirror_yield, \
# trace:mirror_yield_in_flight, \
# trace:mirror_yield_buf_busy, \
# trace:mirror_break_buf_busy, \
# trace:backup_do_cow_enter, \
# trace:backup_do_cow_return, \
# trace:backup_do_cow_skip, \
# trace:backup_do_cow_process, \
# trace:backup_do_cow_read_fail, \
# trace:backup_do_cow_write_fail, \
# trace:qmp_block_job_cancel, \
# trace:qmp_block_job_pause, \
# trace:qmp_block_job_resume, \
# trace:qmp_block_job_complete, \
# trace:block_job_cb, \
# trace:qmp_block_stream, \
# trace:virtio_blk_req_complete, \
# trace:virtio_blk_rw_complete, \
# trace:virtio_blk_handle_write, \
# trace:virtio_blk_handle_read, \
# trace:virtio_blk_submit_multireq, \
# trace:virtio_blk_data_plane_start, \
# trace:virtio_blk_data_plane_stop, \
# trace:virtio_blk_data_plane_process_request, \
# trace:thread_pool_submit, \
# trace:thread_pool_complete, \
# trace:thread_pool_cancel, \
# trace:paio_submit_co, \
# trace:paio_submit, \
# trace:cpu_in, \
# trace:cpu_out, \
# trace:balloon_event, \
# trace:virtio_balloon_handle_output, \
# trace:virtio_balloon_get_config, \
# trace:virtio_balloon_set_config, \
# trace:virtio_balloon_to_target, \
# trace:cpu_set_apic_base, \
# trace:cpu_get_apic_base, \
# trace:apic_report_irq_delivered, \
# trace:apic_reset_irq_delivered, \
# trace:apic_get_irq_delivered, \
# trace:apic_local_deliver, \
# trace:apic_deliver_irq, \
# trace:apic_mem_readl, \
# trace:apic_mem_writel, \
# trace:cs4231_mem_readl_dreg, \
# trace:cs4231_mem_readl_reg, \
# trace:cs4231_mem_writel_reg, \
# trace:cs4231_mem_writel_dreg, \
# trace:nvram_read, \
# trace:nvram_write, \
# trace:ecc_mem_writel_mer, \
# trace:ecc_mem_writel_mdr, \
# trace:ecc_mem_writel_mfsr, \
# trace:ecc_mem_writel_vcr, \
# trace:ecc_mem_writel_dr, \
# trace:ecc_mem_writel_ecr0, \
# trace:ecc_mem_writel_ecr1, \
# trace:ecc_mem_readl_mer, \
# trace:ecc_mem_readl_mdr, \
# trace:ecc_mem_readl_mfsr, \
# trace:ecc_mem_readl_vcr, \
# trace:ecc_mem_readl_mfar0, \
# trace:ecc_mem_readl_mfar1, \
# trace:ecc_mem_readl_dr, \
# trace:ecc_mem_readl_ecr0, \
# trace:ecc_mem_readl_ecr1, \
# trace:ecc_diag_mem_writeb, \
# trace:ecc_diag_mem_readb, \
# trace:fw_cfg_select, \
# trace:fw_cfg_read, \
# trace:fw_cfg_add_file, \
# trace:hd_geometry_lchs_guess, \
# trace:hd_geometry_guess, \
# trace:jazz_led_read, \
# trace:jazz_led_write, \
# trace:xenfb_mouse_event, \
# trace:xenfb_input_connected, \
# trace:lance_mem_readw, \
# trace:lance_mem_writew, \
# trace:slavio_intctl_mem_readl, \
# trace:slavio_intctl_mem_writel, \
# trace:slavio_intctl_mem_writel_clear, \
# trace:slavio_intctl_mem_writel_set, \
# trace:slavio_intctlm_mem_readl, \
# trace:slavio_intctlm_mem_writel, \
# trace:slavio_intctlm_mem_writel_enable, \
# trace:slavio_intctlm_mem_writel_disable, \
# trace:slavio_intctlm_mem_writel_target, \
# trace:slavio_check_interrupts, \
# trace:slavio_set_irq, \
# trace:slavio_set_timer_irq_cpu, \
# trace:ps2_put_keycode, \
# trace:ps2_read_data, \
# trace:ps2_set_ledstate, \
# trace:ps2_reset_keyboard, \
# trace:ps2_write_keyboard, \
# trace:ps2_keyboard_set_translation, \
# trace:ps2_mouse_send_packet, \
# trace:ps2_mouse_event_disabled, \
# trace:ps2_mouse_event, \
# trace:ps2_mouse_fake_event, \
# trace:ps2_write_mouse, \
# trace:ps2_kbd_reset, \
# trace:ps2_mouse_reset, \
# trace:ps2_kbd_init, \
# trace:ps2_mouse_init, \
# trace:slavio_misc_update_irq_raise, \
# trace:slavio_misc_update_irq_lower, \
# trace:slavio_set_power_fail, \
# trace:slavio_cfg_mem_writeb, \
# trace:slavio_cfg_mem_readb, \
# trace:slavio_diag_mem_writeb, \
# trace:slavio_diag_mem_readb, \
# trace:slavio_mdm_mem_writeb, \
# trace:slavio_mdm_mem_readb, \
# trace:slavio_aux1_mem_writeb, \
# trace:slavio_aux1_mem_readb, \
# trace:slavio_aux2_mem_writeb, \
# trace:slavio_aux2_mem_readb, \
# trace:apc_mem_writeb, \
# trace:apc_mem_readb, \
# trace:slavio_sysctrl_mem_writel, \
# trace:slavio_sysctrl_mem_readl, \
# trace:slavio_led_mem_writew, \
# trace:slavio_led_mem_readw, \
# trace:slavio_timer_get_out, \
# trace:slavio_timer_irq, \
# trace:slavio_timer_mem_readl_invalid, \
# trace:slavio_timer_mem_readl, \
# trace:slavio_timer_mem_writel, \
# trace:slavio_timer_mem_writel_limit, \
# trace:slavio_timer_mem_writel_counter_invalid, \
# trace:slavio_timer_mem_writel_status_start, \
# trace:slavio_timer_mem_writel_status_stop, \
# trace:slavio_timer_mem_writel_mode_user, \
# trace:slavio_timer_mem_writel_mode_counter, \
# trace:slavio_timer_mem_writel_mode_invalid, \
# trace:slavio_timer_mem_writel_invalid, \
# trace:jazzio_read, \
# trace:jazzio_write, \
# trace:rc4030_read, \
# trace:rc4030_write, \
# trace:sparc32_dma_set_irq_raise, \
# trace:sparc32_dma_set_irq_lower, \
# trace:sparc32_dma_mem_readl, \
# trace:sparc32_dma_mem_writel, \
# trace:sparc32_dma_enable_raise, \
# trace:sparc32_dma_enable_lower, \
# trace:sun4m_cpu_interrupt, \
# trace:sun4m_cpu_reset_interrupt, \
# trace:sun4m_cpu_set_irq_raise, \
# trace:sun4m_cpu_set_irq_lower, \
# trace:sun4m_iommu_mem_readl, \
# trace:sun4m_iommu_mem_writel, \
# trace:sun4m_iommu_mem_writel_ctrl, \
# trace:sun4m_iommu_mem_writel_tlbflush, \
# trace:sun4m_iommu_mem_writel_pgflush, \
# trace:sun4m_iommu_page_get_flags, \
# trace:sun4m_iommu_translate_pa, \
# trace:sun4m_iommu_bad_addr, \
# trace:usb_packet_state_change, \
# trace:usb_packet_state_fault, \
# trace:usb_port_claim, \
# trace:usb_port_attach, \
# trace:usb_port_detach, \
# trace:usb_port_release, \
# trace:usb_ohci_iso_td_read_failed, \
# trace:usb_ohci_iso_td_head, \
# trace:usb_ohci_iso_td_head_offset, \
# trace:usb_ohci_iso_td_relative_frame_number_neg, \
# trace:usb_ohci_iso_td_relative_frame_number_big, \
# trace:usb_ohci_iso_td_bad_direction, \
# trace:usb_ohci_iso_td_bad_bp_be, \
# trace:usb_ohci_iso_td_bad_cc_not_accessed, \
# trace:usb_ohci_iso_td_bad_cc_overrun, \
# trace:usb_ohci_iso_td_so, \
# trace:usb_ohci_iso_td_data_overrun, \
# trace:usb_ohci_iso_td_data_underrun, \
# trace:usb_ohci_iso_td_nak, \
# trace:usb_ohci_iso_td_bad_response, \
# trace:usb_ohci_port_attach, \
# trace:usb_ohci_port_detach, \
# trace:usb_ohci_port_wakeup, \
# trace:usb_ohci_port_suspend, \
# trace:usb_ohci_port_reset, \
# trace:usb_ohci_remote_wakeup, \
# trace:usb_ohci_reset, \
# trace:usb_ohci_start, \
# trace:usb_ohci_resume, \
# trace:usb_ohci_stop, \
# trace:usb_ohci_exit, \
# trace:usb_ohci_set_ctl, \
# trace:usb_ohci_td_underrun, \
# trace:usb_ohci_td_dev_error, \
# trace:usb_ohci_td_nak, \
# trace:usb_ohci_td_stall, \
# trace:usb_ohci_td_babble, \
# trace:usb_ohci_td_bad_device_response, \
# trace:usb_ohci_td_read_error, \
# trace:usb_ohci_td_bad_direction, \
# trace:usb_ohci_td_skip_async, \
# trace:usb_ohci_td_pkt_hdr, \
# trace:usb_ohci_td_pkt_short, \
# trace:usb_ohci_td_pkt_full, \
# trace:usb_ohci_td_too_many_pending, \
# trace:usb_ohci_td_packet_status, \
# trace:usb_ohci_ed_read_error, \
# trace:usb_ohci_ed_pkt, \
# trace:usb_ohci_ed_pkt_flags, \
# trace:usb_ohci_hcca_read_error, \
# trace:usb_ohci_mem_read_unaligned, \
# trace:usb_ohci_mem_read_bad_offset, \
# trace:usb_ohci_mem_write_unaligned, \
# trace:usb_ohci_mem_write_bad_offset, \
# trace:usb_ohci_process_lists, \
# trace:usb_ohci_bus_eof_timer_failed, \
# trace:usb_ohci_set_frame_interval, \
# trace:usb_ohci_hub_power_up, \
# trace:usb_ohci_hub_power_down, \
# trace:usb_ohci_init_time, \
# trace:usb_ohci_die, \
# trace:usb_ohci_async_complete, \
# trace:usb_ehci_reset, \
# trace:usb_ehci_unrealize, \
# trace:usb_ehci_opreg_read, \
# trace:usb_ehci_opreg_write, \
# trace:usb_ehci_opreg_change, \
# trace:usb_ehci_portsc_read, \
# trace:usb_ehci_portsc_write, \
# trace:usb_ehci_portsc_change, \
# trace:usb_ehci_usbsts, \
# trace:usb_ehci_state, \
# trace:usb_ehci_qh_ptrs, \
# trace:usb_ehci_qh_fields, \
# trace:usb_ehci_qh_bits, \
# trace:usb_ehci_qtd_ptrs, \
# trace:usb_ehci_qtd_fields, \
# trace:usb_ehci_qtd_bits, \
# trace:usb_ehci_itd, \
# trace:usb_ehci_sitd, \
# trace:usb_ehci_port_attach, \
# trace:usb_ehci_port_detach, \
# trace:usb_ehci_port_reset, \
# trace:usb_ehci_port_suspend, \
# trace:usb_ehci_port_wakeup, \
# trace:usb_ehci_port_resume, \
# trace:usb_ehci_queue_action, \
# trace:usb_ehci_packet_action, \
# trace:usb_ehci_irq, \
# trace:usb_ehci_guest_bug, \
# trace:usb_ehci_doorbell_ring, \
# trace:usb_ehci_doorbell_ack, \
# trace:usb_ehci_dma_error, \
# trace:usb_uhci_reset, \
# trace:usb_uhci_exit, \
# trace:usb_uhci_schedule_start, \
# trace:usb_uhci_schedule_stop, \
# trace:usb_uhci_frame_start, \
# trace:usb_uhci_frame_stop_bandwidth, \
# trace:usb_uhci_frame_loop_stop_idle, \
# trace:usb_uhci_frame_loop_continue, \
# trace:usb_uhci_mmio_readw, \
# trace:usb_uhci_mmio_writew, \
# trace:usb_uhci_queue_add, \
# trace:usb_uhci_queue_del, \
# trace:usb_uhci_packet_add, \
# trace:usb_uhci_packet_link_async, \
# trace:usb_uhci_packet_unlink_async, \
# trace:usb_uhci_packet_cancel, \
# trace:usb_uhci_packet_complete_success, \
# trace:usb_uhci_packet_complete_shortxfer, \
# trace:usb_uhci_packet_complete_stall, \
# trace:usb_uhci_packet_complete_babble, \
# trace:usb_uhci_packet_complete_error, \
# trace:usb_uhci_packet_del, \
# trace:usb_uhci_qh_load, \
# trace:usb_uhci_td_load, \
# trace:usb_uhci_td_queue, \
# trace:usb_uhci_td_nextqh, \
# trace:usb_uhci_td_async, \
# trace:usb_uhci_td_complete, \
# trace:usb_xhci_reset, \
# trace:usb_xhci_exit, \
# trace:usb_xhci_run, \
# trace:usb_xhci_stop, \
# trace:usb_xhci_cap_read, \
# trace:usb_xhci_oper_read, \
# trace:usb_xhci_port_read, \
# trace:usb_xhci_runtime_read, \
# trace:usb_xhci_doorbell_read, \
# trace:usb_xhci_oper_write, \
# trace:usb_xhci_port_write, \
# trace:usb_xhci_runtime_write, \
# trace:usb_xhci_doorbell_write, \
# trace:usb_xhci_irq_intx, \
# trace:usb_xhci_irq_msi, \
# trace:usb_xhci_irq_msix, \
# trace:usb_xhci_irq_msix_use, \
# trace:usb_xhci_irq_msix_unuse, \
# trace:usb_xhci_queue_event, \
# trace:usb_xhci_fetch_trb, \
# trace:usb_xhci_port_reset, \
# trace:usb_xhci_port_link, \
# trace:usb_xhci_port_notify, \
# trace:usb_xhci_slot_enable, \
# trace:usb_xhci_slot_disable, \
# trace:usb_xhci_slot_address, \
# trace:usb_xhci_slot_configure, \
# trace:usb_xhci_slot_evaluate, \
# trace:usb_xhci_slot_reset, \
# trace:usb_xhci_ep_enable, \
# trace:usb_xhci_ep_disable, \
# trace:usb_xhci_ep_set_dequeue, \
# trace:usb_xhci_ep_kick, \
# trace:usb_xhci_ep_stop, \
# trace:usb_xhci_ep_reset, \
# trace:usb_xhci_ep_state, \
# trace:usb_xhci_xfer_start, \
# trace:usb_xhci_xfer_async, \
# trace:usb_xhci_xfer_nak, \
# trace:usb_xhci_xfer_retry, \
# trace:usb_xhci_xfer_success, \
# trace:usb_xhci_xfer_error, \
# trace:usb_xhci_unimplemented, \
# trace:usb_desc_device, \
# trace:usb_desc_device_qualifier, \
# trace:usb_desc_config, \
# trace:usb_desc_other_speed_config, \
# trace:usb_desc_string, \
# trace:usb_desc_bos, \
# trace:usb_desc_msos, \
# trace:usb_set_addr, \
# trace:usb_set_config, \
# trace:usb_set_interface, \
# trace:usb_clear_device_feature, \
# trace:usb_set_device_feature, \
# trace:usb_hub_reset, \
# trace:usb_hub_control, \
# trace:usb_hub_get_port_status, \
# trace:usb_hub_set_port_feature, \
# trace:usb_hub_clear_port_feature, \
# trace:usb_hub_attach, \
# trace:usb_hub_detach, \
# trace:usb_hub_status_report, \
# trace:usb_uas_reset, \
# trace:usb_uas_command, \
# trace:usb_uas_response, \
# trace:usb_uas_sense, \
# trace:usb_uas_read_ready, \
# trace:usb_uas_write_ready, \
# trace:usb_uas_xfer_data, \
# trace:usb_uas_scsi_data, \
# trace:usb_uas_scsi_complete, \
# trace:usb_uas_tmf_abort_task, \
# trace:usb_uas_tmf_logical_unit_reset, \
# trace:usb_uas_tmf_unsupported, \
# trace:usb_mtp_reset, \
# trace:usb_mtp_command, \
# trace:usb_mtp_success, \
# trace:usb_mtp_error, \
# trace:usb_mtp_data_in, \
# trace:usb_mtp_xfer, \
# trace:usb_mtp_nak, \
# trace:usb_mtp_stall, \
# trace:usb_mtp_op_get_device_info, \
# trace:usb_mtp_op_open_session, \
# trace:usb_mtp_op_close_session, \
# trace:usb_mtp_op_get_storage_ids, \
# trace:usb_mtp_op_get_storage_info, \
# trace:usb_mtp_op_get_num_objects, \
# trace:usb_mtp_op_get_object_handles, \
# trace:usb_mtp_op_get_object_info, \
# trace:usb_mtp_op_get_object, \
# trace:usb_mtp_op_get_partial_object, \
# trace:usb_mtp_op_unknown, \
# trace:usb_mtp_object_alloc, \
# trace:usb_mtp_object_free, \
# trace:usb_mtp_add_child, \
# trace:usb_mtp_inotify_event, \
# trace:usb_host_open_started, \
# trace:usb_host_open_success, \
# trace:usb_host_open_failure, \
# trace:usb_host_close, \
# trace:usb_host_attach_kernel, \
# trace:usb_host_detach_kernel, \
# trace:usb_host_set_address, \
# trace:usb_host_set_config, \
# trace:usb_host_set_interface, \
# trace:usb_host_claim_interface, \
# trace:usb_host_release_interface, \
# trace:usb_host_req_control, \
# trace:usb_host_req_data, \
# trace:usb_host_req_complete, \
# trace:usb_host_req_emulated, \
# trace:usb_host_req_canceled, \
# trace:usb_host_iso_start, \
# trace:usb_host_iso_stop, \
# trace:usb_host_iso_out_of_bufs, \
# trace:usb_host_reset, \
# trace:usb_host_auto_scan_enabled, \
# trace:usb_host_auto_scan_disabled, \
# trace:usb_host_parse_config, \
# trace:usb_host_parse_interface, \
# trace:usb_host_parse_endpoint, \
# trace:usb_host_parse_error, \
# trace:scsi_req_alloc, \
# trace:scsi_req_cancel, \
# trace:scsi_req_data, \
# trace:scsi_req_data_canceled, \
# trace:scsi_req_dequeue, \
# trace:scsi_req_continue, \
# trace:scsi_req_continue_canceled, \
# trace:scsi_req_parsed, \
# trace:scsi_req_parsed_lba, \
# trace:scsi_req_parse_bad, \
# trace:scsi_req_build_sense, \
# trace:scsi_device_set_ua, \
# trace:scsi_report_luns, \
# trace:scsi_inquiry, \
# trace:scsi_test_unit_ready, \
# trace:scsi_request_sense, \
# trace:vm_state_notify, \
# trace:load_file, \
# trace:runstate_set, \
# trace:system_wakeup_request, \
# trace:qemu_system_shutdown_request, \
# trace:qemu_system_powerdown_request, \
# trace:qcow2_writev_start_req, \
# trace:qcow2_writev_done_req, \
# trace:qcow2_writev_start_part, \
# trace:qcow2_writev_done_part, \
# trace:qcow2_writev_data, \
# trace:qcow2_alloc_clusters_offset, \
# trace:qcow2_handle_copied, \
# trace:qcow2_handle_alloc, \
# trace:qcow2_do_alloc_clusters_offset, \
# trace:qcow2_cluster_alloc_phys, \
# trace:qcow2_cluster_link_l2, \
# trace:qcow2_l2_allocate, \
# trace:qcow2_l2_allocate_get_empty, \
# trace:qcow2_l2_allocate_write_l2, \
# trace:qcow2_l2_allocate_write_l1, \
# trace:qcow2_l2_allocate_done, \
# trace:qcow2_cache_get, \
# trace:qcow2_cache_get_replace_entry, \
# trace:qcow2_cache_get_read, \
# trace:qcow2_cache_get_done, \
# trace:qcow2_cache_flush, \
# trace:qcow2_cache_entry_flush, \
# trace:qed_alloc_l2_cache_entry, \
# trace:qed_unref_l2_cache_entry, \
# trace:qed_find_l2_cache_entry, \
# trace:qed_read_table, \
# trace:qed_read_table_cb, \
# trace:qed_write_table, \
# trace:qed_write_table_cb, \
# trace:qed_need_check_timer_cb, \
# trace:qed_start_need_check_timer, \
# trace:qed_cancel_need_check_timer, \
# trace:qed_aio_complete, \
# trace:qed_aio_setup, \
# trace:qed_aio_next_io, \
# trace:qed_aio_read_data, \
# trace:qed_aio_write_data, \
# trace:qed_aio_write_prefill, \
# trace:qed_aio_write_postfill, \
# trace:qed_aio_write_main, \
# trace:g364fb_read, \
# trace:g364fb_write, \
# trace:grlib_gptimer_enable, \
# trace:grlib_gptimer_disabled, \
# trace:grlib_gptimer_restart, \
# trace:grlib_gptimer_set_scaler, \
# trace:grlib_gptimer_hit, \
# trace:grlib_gptimer_readl, \
# trace:grlib_gptimer_writel, \
# trace:grlib_irqmp_check_irqs, \
# trace:grlib_irqmp_ack, \
# trace:grlib_irqmp_set_irq, \
# trace:grlib_irqmp_readl_unknown, \
# trace:grlib_irqmp_writel_unknown, \
# trace:grlib_apbuart_event, \
# trace:grlib_apbuart_writel_unknown, \
# trace:grlib_apbuart_readl_unknown, \
# trace:leon3_set_irq, \
# trace:leon3_reset_irq, \
# trace:spice_vmc_write, \
# trace:spice_vmc_read, \
# trace:spice_vmc_register_interface, \
# trace:spice_vmc_unregister_interface, \
# trace:spice_vmc_event, \
# trace:lm32_pic_raise_irq, \
# trace:lm32_pic_lower_irq, \
# trace:lm32_pic_interrupt, \
# trace:lm32_pic_set_im, \
# trace:lm32_pic_set_ip, \
# trace:lm32_pic_get_im, \
# trace:lm32_pic_get_ip, \
# trace:lm32_juart_get_jtx, \
# trace:lm32_juart_set_jtx, \
# trace:lm32_juart_get_jrx, \
# trace:lm32_juart_set_jrx, \

    
# trace:lm32_timer_hit, \
# trace:lm32_timer_irq_state, \

# trace:lm32_uart_irq_state, \
# trace:mptsas_command_complete, \
# trace:mptsas_diag_read, \
# trace:mptsas_diag_write, \
# trace:mptsas_irq_intx, \
# trace:mptsas_irq_msi, \
# trace:mptsas_mmio_read, \
# trace:mptsas_mmio_unhandled_read, \
# trace:mptsas_mmio_unhandled_write, \
# trace:mptsas_mmio_write, \
# trace:mptsas_process_message, \
# trace:mptsas_process_scsi_io_request, \
# trace:mptsas_reset, \
# trace:mptsas_scsi_overflow, \
# trace:mptsas_sgl_overflow, \
# trace:mptsas_unhandled_cmd, \
# trace:mptsas_unhandled_doorbell_cmd, \
# trace:mptsas_config_sas_device, \
# trace:mptsas_config_sas_phy, \
# trace:megasas_init_firmware, \
# trace:megasas_init_queue, \
# trace:megasas_initq_map_failed, \
# trace:megasas_initq_mapped, \
# trace:megasas_initq_mismatch, \
# trace:megasas_qf_mapped, \
# trace:megasas_qf_new, \
# trace:megasas_qf_busy, \
# trace:megasas_qf_enqueue, \
# trace:megasas_qf_update, \
# trace:megasas_qf_map_failed, \
# trace:megasas_qf_complete_noirq, \
# trace:megasas_qf_complete, \
# trace:megasas_frame_busy, \
# trace:megasas_unhandled_frame_cmd, \
# trace:megasas_handle_scsi, \
# trace:megasas_scsi_target_not_present, \
# trace:megasas_scsi_invalid_cdb_len, \
# trace:megasas_iov_read_overflow, \
# trace:megasas_iov_write_overflow, \
# trace:megasas_iov_read_underflow, \
# trace:megasas_iov_write_underflow, \
# trace:megasas_scsi_req_alloc_failed, \
# trace:megasas_scsi_read_start, \
# trace:megasas_scsi_write_start, \
# trace:megasas_scsi_nodata, \
# trace:megasas_scsi_complete, \
# trace:megasas_command_complete, \
# trace:megasas_handle_io, \
# trace:megasas_io_target_not_present, \
# trace:megasas_io_read_start, \
# trace:megasas_io_write_start, \
# trace:megasas_io_complete, \
# trace:megasas_iovec_sgl_overflow, \
# trace:megasas_iovec_sgl_underflow, \
# trace:megasas_iovec_sgl_invalid, \
# trace:megasas_iovec_overflow, \
# trace:megasas_iovec_underflow, \
# trace:megasas_handle_dcmd, \
# trace:megasas_finish_dcmd, \
# trace:megasas_dcmd_req_alloc_failed, \
# trace:megasas_dcmd_internal_submit, \
# trace:megasas_dcmd_internal_finish, \
# trace:megasas_dcmd_internal_invalid, \
# trace:megasas_dcmd_unhandled, \
# trace:megasas_dcmd_zero_sge, \
# trace:megasas_dcmd_invalid_sge, \
# trace:megasas_dcmd_invalid_xfer_len, \
# trace:megasas_dcmd_enter, \
# trace:megasas_dcmd_dummy, \
# trace:megasas_dcmd_set_fw_time, \
# trace:megasas_dcmd_pd_get_list, \
# trace:megasas_dcmd_ld_get_list, \
# trace:megasas_dcmd_ld_get_info, \
# trace:megasas_dcmd_ld_list_query, \
# trace:megasas_dcmd_pd_get_info, \
# trace:megasas_dcmd_pd_list_query, \
# trace:megasas_dcmd_reset_ld, \
# trace:megasas_dcmd_unsupported, \
# trace:megasas_abort_frame, \
# trace:megasas_abort_no_cmd, \
# trace:megasas_abort_invalid_context, \
# trace:megasas_reset, \
# trace:megasas_init, \
# trace:megasas_msix_raise, \
# trace:megasas_msi_raise, \
# trace:megasas_irq_lower, \
# trace:megasas_irq_raise, \
# trace:megasas_intr_enabled, \
# trace:megasas_intr_disabled, \
# trace:megasas_msix_enabled, \
# trace:megasas_msi_enabled, \
# trace:megasas_mmio_readl, \
# trace:megasas_mmio_invalid_readl, \
# trace:megasas_mmio_writel, \
# trace:megasas_mmio_invalid_writel, \

# trace:milkymist_ac97_pulse_irq_crrequest, \
# trace:milkymist_ac97_pulse_irq_crreply, \
# trace:milkymist_ac97_pulse_irq_dmaw, \
# trace:milkymist_ac97_pulse_irq_dmar, \
# trace:milkymist_ac97_in_cb, \
# trace:milkymist_ac97_in_cb_transferred, \
# trace:milkymist_ac97_out_cb, \
# trace:milkymist_ac97_out_cb_transferred, \

# trace:milkymist_minimac2_tx_frame, \
# trace:milkymist_minimac2_rx_frame, \
# trace:milkymist_minimac2_rx_transfer, \
# trace:milkymist_minimac2_raise_irq_rx, \
# trace:milkymist_minimac2_lower_irq_rx, \
# trace:milkymist_minimac2_pulse_irq_tx, \



# trace:milkymist_pfpu_vectout, \
# trace:milkymist_pfpu_pulse_irq, \
# trace:milkymist_softusb_mevt, \
# trace:milkymist_softusb_kevt, \
# trace:milkymist_softusb_pulse_irq, \
# trace:milkymist_sysctl_icap_write, \
# trace:milkymist_sysctl_start_timer0, \
# trace:milkymist_sysctl_stop_timer0, \
# trace:milkymist_sysctl_start_timer1, \
# trace:milkymist_sysctl_stop_timer1, \
# trace:milkymist_sysctl_pulse_irq_timer0, \
# trace:milkymist_sysctl_pulse_irq_timer1, \
# trace:milkymist_tmu2_start, \
# trace:milkymist_tmu2_pulse_irq, \
# trace:milkymist_uart_raise_irq, \
# trace:milkymist_uart_lower_irq, \
# trace:mipsnet_send, \
# trace:mipsnet_receive, \
# trace:mipsnet_read, \
# trace:mipsnet_write, \
# trace:mipsnet_irq, \
# trace:pc87312_io_read, \
# trace:pc87312_io_write, \
# trace:pc87312_info_floppy, \
# trace:pc87312_info_ide, \
# trace:pc87312_info_parallel, \
# trace:pc87312_info_serial, \
# trace:pvscsi_ring_init_data, \
# trace:pvscsi_ring_init_msg, \
# trace:pvscsi_ring_flush_cmp, \
# trace:pvscsi_ring_flush_msg, \
# trace:pvscsi_update_irq_level, \
# trace:pvscsi_update_irq_msi, \
# trace:pvscsi_cmp_ring_put, \
# trace:pvscsi_msg_ring_put, \
# trace:pvscsi_complete_request, \
# trace:pvscsi_get_sg_list, \
# trace:pvscsi_get_next_sg_elem, \
# trace:pvscsi_command_complete_not_found, \
# trace:pvscsi_command_complete_data_run, \
# trace:pvscsi_command_complete_sense_len, \
# trace:pvscsi_convert_sglist, \
# trace:pvscsi_process_req_descr, \
# trace:pvscsi_process_req_descr_unknown_device, \
# trace:pvscsi_process_req_descr_invalid_dir, \
# trace:pvscsi_process_io, \
# trace:pvscsi_on_cmd_noimpl, \
# trace:pvscsi_on_cmd_reset_dev, \
# trace:pvscsi_on_cmd_arrived, \
# trace:pvscsi_on_cmd_abort, \
# trace:pvscsi_on_cmd_unknown, \
# trace:pvscsi_on_cmd_unknown_data, \
# trace:pvscsi_io_write, \
# trace:pvscsi_io_write_unknown, \
# trace:pvscsi_io_read, \
# trace:pvscsi_io_read_unknown, \
# trace:pvscsi_init_msi_fail, \
# trace:pvscsi_state, \
# trace:pvscsi_tx_rings_ppn, \
# trace:pvscsi_tx_rings_num_pages, \
# trace:xen_ram_alloc, \
# trace:xen_client_set_memory, \
# trace:xen_ioreq_server_create, \
# trace:xen_ioreq_server_destroy, \
# trace:xen_ioreq_server_state, \
# trace:xen_map_mmio_range, \
# trace:xen_unmap_mmio_range, \
# trace:xen_map_portio_range, \
# trace:xen_unmap_portio_range, \
# trace:xen_map_pcidev, \
# trace:xen_unmap_pcidev, \
# trace:handle_ioreq, \
# trace:handle_ioreq_read, \
# trace:handle_ioreq_write, \
# trace:cpu_ioreq_pio, \
# trace:cpu_ioreq_pio_read_reg, \
# trace:cpu_ioreq_pio_write_reg, \
# trace:cpu_ioreq_move, \
# trace:xen_map_cache, \
# trace:xen_remap_bucket, \
# trace:xen_map_cache_return, \
# trace:xen_platform_log, \
# trace:qemu_coroutine_enter, \
# trace:qemu_coroutine_yield, \
# trace:qemu_coroutine_terminate, \
# trace:qemu_co_queue_run_restart, \
# trace:qemu_co_queue_next, \
# trace:qemu_co_mutex_lock_entry, \
# trace:qemu_co_mutex_lock_return, \
# trace:qemu_co_mutex_unlock_entry, \
# trace:qemu_co_mutex_unlock_return, \
# trace:escc_put_queue, \
# trace:escc_get_queue, \
# trace:escc_update_irq, \
# trace:escc_update_parameters, \
# trace:escc_mem_writeb_ctrl, \
# trace:escc_mem_writeb_data, \
# trace:escc_mem_readb_ctrl, \
# trace:escc_mem_readb_data, \
# trace:escc_serial_receive_byte, \
# trace:escc_sunkbd_event_in, \
# trace:escc_sunkbd_event_out, \
# trace:escc_kbd_command, \
# trace:escc_sunmouse_event, \
# trace:esp_error_fifo_overrun, \
# trace:esp_error_unhandled_command, \
# trace:esp_error_invalid_write, \
# trace:esp_raise_irq, \
# trace:esp_lower_irq, \
# trace:esp_dma_enable, \
# trace:esp_dma_disable, \
# trace:esp_get_cmd, \
# trace:esp_do_busid_cmd, \
# trace:esp_handle_satn_stop, \
# trace:esp_write_response, \
# trace:esp_do_dma, \
# trace:esp_command_complete, \
# trace:esp_command_complete_unexpected, \
# trace:esp_command_complete_fail, \
# trace:esp_transfer_data, \
# trace:esp_handle_ti, \
# trace:esp_handle_ti_cmd, \
# trace:esp_mem_readb, \
# trace:esp_mem_writeb, \
# trace:esp_mem_writeb_cmd_nop, \
# trace:esp_mem_writeb_cmd_flush, \
# trace:esp_mem_writeb_cmd_reset, \
# trace:esp_mem_writeb_cmd_bus_reset, \
# trace:esp_mem_writeb_cmd_iccs, \
# trace:esp_mem_writeb_cmd_msgacc, \
# trace:esp_mem_writeb_cmd_pad, \
# trace:esp_mem_writeb_cmd_satn, \
# trace:esp_mem_writeb_cmd_rstatn, \
# trace:esp_mem_writeb_cmd_sel, \
# trace:esp_mem_writeb_cmd_selatn, \
# trace:esp_mem_writeb_cmd_selatns, \
# trace:esp_mem_writeb_cmd_ensel, \
# trace:esp_mem_writeb_cmd_dissel, \
# trace:esp_pci_error_invalid_dma_direction, \
# trace:esp_pci_error_invalid_read, \
# trace:esp_pci_error_invalid_write, \
# trace:esp_pci_error_invalid_write_dma, \
# trace:esp_pci_dma_read, \
# trace:esp_pci_dma_write, \
# trace:esp_pci_dma_idle, \
# trace:esp_pci_dma_blast, \
# trace:esp_pci_dma_abort, \
# trace:esp_pci_dma_start, \
# trace:esp_pci_sbac_read, \
# trace:esp_pci_sbac_write, \
# trace:handle_qmp_command, \
# trace:monitor_protocol_emitter, \
# trace:monitor_protocol_event_handler, \
# trace:monitor_protocol_event_emit, \
# trace:monitor_protocol_event_queue, \
# trace:monitor_protocol_event_throttle, \
# trace:open_eth_mii_write, \
# trace:open_eth_mii_read, \
# trace:open_eth_update_irq, \
# trace:open_eth_receive, \
# trace:open_eth_receive_mcast, \
# trace:open_eth_receive_reject, \
# trace:open_eth_receive_desc, \
# trace:open_eth_start_xmit, \
# trace:open_eth_reg_read, \
# trace:open_eth_reg_write, \
# trace:open_eth_desc_read, \
# trace:open_eth_desc_write, \
# trace:v9fs_rerror, \
# trace:v9fs_version, \
# trace:v9fs_version_return, \
# trace:v9fs_attach, \
# trace:v9fs_attach_return, \
# trace:v9fs_stat, \
# trace:v9fs_stat_return, \
# trace:v9fs_getattr, \
# trace:v9fs_getattr_return, \
# trace:v9fs_walk, \
# trace:v9fs_walk_return, \
# trace:v9fs_open, \
# trace:v9fs_open_return, \
# trace:v9fs_lcreate, \
# trace:v9fs_lcreate_return, \
# trace:v9fs_fsync, \
# trace:v9fs_clunk, \
# trace:v9fs_read, \
# trace:v9fs_read_return, \
# trace:v9fs_readdir, \
# trace:v9fs_readdir_return, \
# trace:v9fs_write, \
# trace:v9fs_write_return, \
# trace:v9fs_create, \
# trace:v9fs_create_return, \
# trace:v9fs_symlink, \
# trace:v9fs_symlink_return, \
# trace:v9fs_flush, \
# trace:v9fs_link, \
# trace:v9fs_remove, \
# trace:v9fs_wstat, \
# trace:v9fs_mknod, \
# trace:v9fs_mknod_return, \
# trace:v9fs_lock, \
# trace:v9fs_lock_return, \
# trace:v9fs_getlock, \
# trace:v9fs_getlock_return, \
# trace:v9fs_mkdir, \
# trace:v9fs_mkdir_return, \
# trace:v9fs_xattrwalk, \
# trace:v9fs_xattrwalk_return, \
# trace:v9fs_xattrcreate, \
# trace:v9fs_readlink, \
# trace:v9fs_readlink_return, \
# trace:mmu_helper_dfault, \
# trace:mmu_helper_dprot, \
# trace:mmu_helper_dmiss, \
# trace:mmu_helper_tfault, \
# trace:mmu_helper_tmiss, \
# trace:mmu_helper_get_phys_addr_code, \
# trace:mmu_helper_get_phys_addr_data, \
# trace:mmu_helper_mmu_fault, \
# trace:int_helper_set_softint, \
# trace:int_helper_clear_softint, \
# trace:int_helper_write_softint, \
# trace:int_helper_icache_freeze, \
# trace:int_helper_dcache_freeze, \
# trace:win_helper_gregset_error, \
# trace:win_helper_switch_pstate, \
# trace:win_helper_no_switch_pstate, \
# trace:win_helper_wrpil, \
# trace:win_helper_done, \
# trace:win_helper_retry, \
# trace:dma_blk_io, \
# trace:dma_aio_cancel, \
# trace:dma_complete, \
# trace:dma_blk_cb, \
# trace:dma_map_wait, \
# trace:console_gfx_new, \
# trace:console_putchar_csi, \
# trace:console_putchar_unhandled, \
# trace:console_txt_new, \
# trace:console_select, \
# trace:console_refresh, \
# trace:displaysurface_create, \
# trace:displaysurface_create_from, \
# trace:displaysurface_create_pixman, \
# trace:displaysurface_free, \
# trace:displaychangelistener_register, \
# trace:displaychangelistener_unregister, \
# trace:ppm_save, \
# trace:gd_switch, \
# trace:gd_update, \
# trace:gd_key_event, \
# trace:gd_grab, \
# trace:gd_ungrab, \
# trace:vnc_key_guest_leds, \
# trace:vnc_key_map_init, \
# trace:vnc_key_event_ext, \
# trace:vnc_key_event_map, \
# trace:vnc_key_sync_numlock, \
# trace:vnc_key_sync_capslock, \
# trace:input_event_key_number, \
# trace:input_event_key_qcode, \
# trace:input_event_btn, \
# trace:input_event_rel, \
# trace:input_event_abs, \
# trace:input_event_sync, \
# trace:input_mouse_mode, \
# trace:vmware_value_read, \
# trace:vmware_value_write, \
# trace:vmware_palette_read, \
# trace:vmware_palette_write, \
# trace:vmware_scratch_read, \
# trace:vmware_scratch_write, \
# trace:vmware_setmode, \
# trace:virtio_gpu_features, \
# trace:virtio_gpu_cmd_get_display_info, \
# trace:virtio_gpu_cmd_get_caps, \
# trace:virtio_gpu_cmd_set_scanout, \
# trace:virtio_gpu_cmd_res_create_2d, \
# trace:virtio_gpu_cmd_res_create_3d, \
# trace:virtio_gpu_cmd_res_unref, \
# trace:virtio_gpu_cmd_res_back_attach, \
# trace:virtio_gpu_cmd_res_back_detach, \
# trace:virtio_gpu_cmd_res_xfer_toh_2d, \
# trace:virtio_gpu_cmd_res_xfer_toh_3d, \
# trace:virtio_gpu_cmd_res_xfer_fromh_3d, \
# trace:virtio_gpu_cmd_res_flush, \
# trace:virtio_gpu_cmd_ctx_create, \
# trace:virtio_gpu_cmd_ctx_destroy, \
# trace:virtio_gpu_cmd_ctx_res_attach, \
# trace:virtio_gpu_cmd_ctx_res_detach, \
# trace:virtio_gpu_cmd_ctx_submit, \
# trace:virtio_gpu_update_cursor, \
# trace:virtio_gpu_fence_ctrl, \
# trace:virtio_gpu_fence_resp, \
# trace:qemu_loadvm_state_section, \
# trace:qemu_loadvm_state_section_command, \
# trace:qemu_loadvm_state_section_partend, \
# trace:qemu_loadvm_state_main, \
# trace:qemu_loadvm_state_main_quit_parent, \
# trace:qemu_loadvm_state_post_main, \
# trace:qemu_loadvm_state_section_startfull, \
# trace:qemu_savevm_send_packaged, \
# trace:loadvm_handle_cmd_packaged, \
# trace:loadvm_handle_cmd_packaged_main, \
# trace:loadvm_handle_cmd_packaged_received, \
# trace:loadvm_postcopy_handle_advise, \
# trace:loadvm_postcopy_handle_listen, \
# trace:loadvm_postcopy_handle_run, \
# trace:loadvm_postcopy_handle_run_cpu_sync, \
# trace:loadvm_postcopy_handle_run_vmstart, \
# trace:loadvm_postcopy_ram_handle_discard, \
# trace:loadvm_postcopy_ram_handle_discard_end, \
# trace:loadvm_postcopy_ram_handle_discard_header, \
# trace:loadvm_process_command, \
# trace:loadvm_process_command_ping, \
# trace:postcopy_ram_listen_thread_exit, \
# trace:postcopy_ram_listen_thread_start, \
# trace:qemu_savevm_send_postcopy_advise, \
# trace:qemu_savevm_send_postcopy_ram_discard, \
# trace:savevm_command_send, \
# trace:savevm_section_start, \
# trace:savevm_section_end, \
# trace:savevm_section_skip, \
# trace:savevm_send_open_return_path, \
# trace:savevm_send_ping, \
# trace:savevm_send_postcopy_listen, \
# trace:savevm_send_postcopy_run, \
# trace:savevm_state_begin, \
# trace:savevm_state_header, \
# trace:savevm_state_iterate, \
# trace:savevm_state_cleanup, \
# trace:savevm_state_complete_precopy, \
# trace:vmstate_save, \
# trace:vmstate_load, \
# trace:qemu_announce_self_iter, \
# trace:vmstate_load_field_error, \
# trace:vmstate_load_state, \
# trace:vmstate_load_state_end, \
# trace:vmstate_load_state_field, \
# trace:vmstate_subsection_load, \
# trace:vmstate_subsection_load_bad, \
# trace:vmstate_subsection_load_good, \
# trace:qemu_file_fclose, \
# trace:get_queued_page, \
# trace:get_queued_page_not_dirty, \
# trace:migration_bitmap_sync_start, \
# trace:migration_bitmap_sync_end, \
# trace:migration_throttle, \
# trace:ram_load_postcopy_loop, \
# trace:ram_postcopy_send_discard_bitmap, \
# trace:ram_save_queue_pages, \
# trace:qxl_interface_set_mm_time, \
# trace:qxl_io_write_vga, \
# trace:qxl_create_guest_primary, \
# trace:qxl_create_guest_primary_rest, \
# trace:qxl_destroy_primary, \
# trace:qxl_enter_vga_mode, \
# trace:qxl_exit_vga_mode, \
# trace:qxl_hard_reset, \
# trace:qxl_interface_async_complete_io, \
# trace:qxl_interface_attach_worker, \
# trace:qxl_interface_get_init_info, \
# trace:qxl_interface_set_compression_level, \
# trace:qxl_interface_update_area_complete, \
# trace:qxl_interface_update_area_complete_rest, \
# trace:qxl_interface_update_area_complete_overflow, \
# trace:qxl_interface_update_area_complete_schedule_bh, \
# trace:qxl_io_destroy_primary_ignored, \
# trace:qxl_io_log, \
# trace:qxl_io_read_unexpected, \
# trace:qxl_io_unexpected_vga_mode, \
# trace:qxl_io_write, \
# trace:qxl_memslot_add_guest, \
# trace:qxl_post_load, \
# trace:qxl_pre_load, \
# trace:qxl_pre_save, \
# trace:qxl_reset_surfaces, \
# trace:qxl_ring_command_check, \
# trace:qxl_ring_command_get, \
# trace:qxl_ring_command_req_notification, \
# trace:qxl_ring_cursor_check, \
# trace:qxl_ring_cursor_get, \
# trace:qxl_ring_cursor_req_notification, \
# trace:qxl_ring_res_push, \
# trace:qxl_ring_res_push_rest, \
# trace:qxl_ring_res_put, \
# trace:qxl_set_mode, \
# trace:qxl_soft_reset, \
# trace:qxl_spice_destroy_surfaces_complete, \
# trace:qxl_spice_destroy_surfaces, \
# trace:qxl_spice_destroy_surface_wait_complete, \
# trace:qxl_spice_destroy_surface_wait, \
# trace:qxl_spice_flush_surfaces_async, \
# trace:qxl_spice_monitors_config, \
# trace:qxl_spice_loadvm_commands, \
# trace:qxl_spice_oom, \
# trace:qxl_spice_reset_cursor, \
# trace:qxl_spice_reset_image_cache, \
# trace:qxl_spice_reset_memslots, \
# trace:qxl_spice_update_area, \
# trace:qxl_spice_update_area_rest, \
# trace:qxl_surfaces_dirty, \
# trace:qxl_send_events, \
# trace:qxl_send_events_vm_stopped, \
# trace:qxl_set_guest_bug, \
# trace:qxl_interrupt_client_monitors_config, \
# trace:qxl_client_monitors_config_unsupported_by_guest, \
# trace:qxl_client_monitors_config_unsupported_by_device, \
# trace:qxl_client_monitors_config_capped, \
# trace:qxl_client_monitors_config_crc, \
# trace:qxl_set_client_capabilities_unsupported_by_revision, \
# trace:qemu_spice_add_memslot, \
# trace:qemu_spice_del_memslot, \
# trace:qemu_spice_create_primary_surface, \
# trace:qemu_spice_destroy_primary_surface, \
# trace:qemu_spice_wakeup, \
# trace:qemu_spice_create_update, \
# trace:qxl_render_blit, \
# trace:qxl_render_guest_primary_resized, \
# trace:qxl_render_update_area_done, \
# trace:spapr_pci_msi, \
# trace:spapr_pci_msi_setup, \
# trace:spapr_pci_rtas_ibm_change_msi, \
# trace:spapr_pci_rtas_ibm_query_interrupt_source_number, \
# trace:spapr_pci_msi_write, \
# trace:spapr_pci_lsi_set, \
# trace:spapr_pci_msi_retry, \
# trace:pci_update_mappings_del, \
# trace:pci_update_mappings_add, \
# trace:pcnet_s_reset, \
# trace:pcnet_user_int, \
# trace:pcnet_isr_change, \
# trace:pcnet_init, \
# trace:pcnet_rlen_tlen, \
# trace:pcnet_ss32_rdra_tdra, \
# trace:pcnet_aprom_writeb, \
# trace:pcnet_aprom_readb, \
# trace:pcnet_ioport_read, \
# trace:pcnet_ioport_write, \
# trace:pcnet_mmio_writeb, \
# trace:pcnet_mmio_writew, \
# trace:pcnet_mmio_writel, \
# trace:pcnet_mmio_readb, \
# trace:pcnet_mmio_readw, \
# trace:pcnet_mmio_readl, \
# trace:xics_icp_check_ipi, \
# trace:xics_icp_accept, \
# trace:xics_icp_eoi, \
# trace:xics_icp_irq, \
# trace:xics_icp_raise, \
# trace:xics_set_irq_msi, \
# trace:xics_masked_pending, \
# trace:xics_set_irq_lsi, \
# trace:xics_ics_write_xive, \
# trace:xics_ics_reject, \
# trace:xics_ics_eoi, \
# trace:xics_alloc, \
# trace:xics_alloc_block, \
# trace:xics_ics_free, \
# trace:xics_ics_free_warn, \
# trace:spapr_cas_failed, \
# trace:spapr_cas_continue, \
# trace:spapr_cas_pvr_try, \
# trace:spapr_cas_pvr, \
# trace:spapr_iommu_put, \
# trace:spapr_iommu_get, \
# trace:spapr_iommu_indirect, \
# trace:spapr_iommu_stuff, \
# trace:spapr_iommu_pci_put, \
# trace:spapr_iommu_pci_get, \
# trace:spapr_iommu_pci_indirect, \
# trace:spapr_iommu_pci_stuff, \
# trace:spapr_iommu_xlate, \
# trace:spapr_iommu_new_table, \
# trace:ppc_tb_adjust, \
# trace:prep_io_800_writeb, \
# trace:prep_io_800_readb, \
# trace:buffer_resize, \
# trace:buffer_move_empty, \
# trace:buffer_move, \
# trace:buffer_free, \
# trace:hbitmap_iter_skip_words, \
# trace:hbitmap_reset, \
# trace:hbitmap_set, \
# trace:get_skeys_nonzero, \
# trace:set_skeys_nonzero, \
# trace:ioinst, \
# trace:ioinst_sch_id, \
# trace:ioinst_chp_id, \
# trace:ioinst_chsc_cmd, \
# trace:css_enable_facility, \
# trace:css_crw, \
# trace:css_chpid_add, \
# trace:css_new_image, \
# trace:css_assign_subch, \
# trace:css_io_interrupt, \
# trace:css_adapter_interrupt, \
# trace:virtio_ccw_interpret_ccw, \
# trace:virtio_ccw_new_device, \
# trace:flic_create_device, \
# trace:flic_no_device_api, \
# trace:flic_reset_failed, \
# trace:await_return_path_close_on_source_close, \
# trace:await_return_path_close_on_source_joining, \
# trace:migrate_set_state, \
# trace:migrate_fd_cleanup, \
# trace:migrate_fd_error, \
# trace:migrate_fd_cancel, \
# trace:migrate_handle_rp_req_pages, \
# trace:migrate_pending, \
# trace:migrate_send_rp_message, \
# trace:migration_completion_file_err, \
# trace:migration_completion_postcopy_end, \
# trace:migration_completion_postcopy_end_after_complete, \
# trace:migration_completion_postcopy_end_before_rp, \
# trace:migration_completion_postcopy_end_after_rp, \
# trace:migration_thread_after_loop, \
# trace:migration_thread_file_err, \
# trace:migration_thread_setup_complete, \
# trace:open_return_path_on_source, \
# trace:open_return_path_on_source_continue, \
# trace:postcopy_start, \
# trace:postcopy_start_set_run, \
# trace:source_return_path_thread_bad_end, \
# trace:source_return_path_thread_end, \
# trace:source_return_path_thread_entry, \
# trace:source_return_path_thread_loop_top, \
# trace:source_return_path_thread_pong, \
# trace:source_return_path_thread_shut, \
# trace:migrate_global_state_post_load, \
# trace:migrate_global_state_pre_save, \
# trace:migration_thread_low_pending, \
# trace:migrate_state_too_big, \
# trace:migrate_transferred, \
# trace:process_incoming_migration_co_end, \
# trace:process_incoming_migration_co_postcopy_end_main, \
# trace:qemu_rdma_accept_incoming_migration, \
# trace:qemu_rdma_accept_incoming_migration_accepted, \
# trace:qemu_rdma_accept_pin_state, \
# trace:qemu_rdma_accept_pin_verbsc, \
# trace:qemu_rdma_block_for_wrid_miss, \
# trace:qemu_rdma_block_for_wrid_miss_b, \
# trace:qemu_rdma_cleanup_disconnect, \
# trace:qemu_rdma_cleanup_waiting_for_disconnect, \
# trace:qemu_rdma_close, \
# trace:qemu_rdma_connect_pin_all_requested, \
# trace:qemu_rdma_connect_pin_all_outcome, \
# trace:qemu_rdma_dest_init_trying, \
# trace:qemu_rdma_dump_gid, \
# trace:qemu_rdma_exchange_get_response_start, \
# trace:qemu_rdma_exchange_get_response_none, \
# trace:qemu_rdma_exchange_send_issue_callback, \
# trace:qemu_rdma_exchange_send_waiting, \
# trace:qemu_rdma_exchange_send_received, \
# trace:qemu_rdma_fill, \
# trace:qemu_rdma_init_ram_blocks, \
# trace:qemu_rdma_poll_recv, \
# trace:qemu_rdma_poll_write, \
# trace:qemu_rdma_poll_other, \
# trace:qemu_rdma_post_send_control, \
# trace:qemu_rdma_register_and_get_keys, \
# trace:qemu_rdma_registration_handle_compress, \
# trace:qemu_rdma_registration_handle_finished, \
# trace:qemu_rdma_registration_handle_ram_blocks, \
# trace:qemu_rdma_registration_handle_ram_blocks_loop, \
# trace:qemu_rdma_registration_handle_register, \
# trace:qemu_rdma_registration_handle_register_loop, \
# trace:qemu_rdma_registration_handle_register_rkey, \
# trace:qemu_rdma_registration_handle_unregister, \
# trace:qemu_rdma_registration_handle_unregister_loop, \
# trace:qemu_rdma_registration_handle_unregister_success, \
# trace:qemu_rdma_registration_handle_wait, \
# trace:qemu_rdma_registration_start, \
# trace:qemu_rdma_registration_stop, \
# trace:qemu_rdma_registration_stop_ram, \
# trace:qemu_rdma_resolve_host_trying, \
# trace:qemu_rdma_signal_unregister_append, \
# trace:qemu_rdma_signal_unregister_already, \
# trace:qemu_rdma_unregister_waiting_inflight, \
# trace:qemu_rdma_unregister_waiting_proc, \
# trace:qemu_rdma_unregister_waiting_send, \
# trace:qemu_rdma_unregister_waiting_complete, \
# trace:qemu_rdma_write_flush, \
# trace:qemu_rdma_write_one_block, \
# trace:qemu_rdma_write_one_post, \
# trace:qemu_rdma_write_one_queue_full, \
# trace:qemu_rdma_write_one_recvregres, \
# trace:qemu_rdma_write_one_sendreg, \
# trace:qemu_rdma_write_one_top, \
# trace:qemu_rdma_write_one_zero, \
# trace:rdma_add_block, \
# trace:rdma_block_notification_handle, \
# trace:rdma_delete_block, \
# trace:rdma_start_incoming_migration, \
# trace:rdma_start_incoming_migration_after_dest_init, \
# trace:rdma_start_incoming_migration_after_rdma_listen, \
# trace:rdma_start_outgoing_migration_after_rdma_connect, \
# trace:rdma_start_outgoing_migration_after_rdma_source_init, \
# trace:postcopy_discard_send_finish, \
# trace:postcopy_discard_send_range, \
# trace:postcopy_ram_discard_range, \
# trace:postcopy_cleanup_range, \
# trace:postcopy_init_range, \
# trace:postcopy_nhp_range, \
# trace:postcopy_place_page, \
# trace:postcopy_place_page_zero, \
# trace:postcopy_ram_enable_notify, \
# trace:postcopy_ram_fault_thread_entry, \
# trace:postcopy_ram_fault_thread_exit, \
# trace:postcopy_ram_fault_thread_quit, \
# trace:postcopy_ram_fault_thread_request, \
# trace:postcopy_ram_incoming_cleanup_closeuf, \
# trace:postcopy_ram_incoming_cleanup_entry, \
# trace:postcopy_ram_incoming_cleanup_exit, \
# trace:postcopy_ram_incoming_cleanup_join, \
# trace:kvm_ioctl, \
# trace:kvm_vm_ioctl, \
# trace:kvm_vcpu_ioctl, \
# trace:kvm_run_exit, \
# trace:kvm_device_ioctl, \
# trace:kvm_failed_reg_get, \
# trace:kvm_failed_reg_set, \
# trace:kvm_failed_spr_set, \
# trace:kvm_failed_spr_get, \
# trace:exec_tb, \
# trace:exec_tb_nocache, \
# trace:exec_tb_exit, \
# trace:translate_block, \
# trace:object_dynamic_cast_assert, \
# trace:object_class_dynamic_cast_assert, \
# trace:xen_pv_mmio_read, \
# trace:xen_pv_mmio_write, \
# trace:pci_cfg_read, \
# trace:pci_cfg_write, \
# trace:vfio_intx_interrupt, \
# trace:vfio_intx_eoi, \
# trace:vfio_intx_enable_kvm, \
# trace:vfio_intx_disable_kvm, \
# trace:vfio_intx_update, \
# trace:vfio_intx_enable, \
# trace:vfio_intx_disable, \
# trace:vfio_msi_interrupt, \
# trace:vfio_msix_vector_do_use, \
# trace:vfio_msix_vector_release, \
# trace:vfio_msix_enable, \
# trace:vfio_msix_pba_disable, \
# trace:vfio_msix_pba_enable, \
# trace:vfio_msix_disable, \
# trace:vfio_msix_fixup, \
# trace:vfio_msi_enable, \
# trace:vfio_msi_disable, \
# trace:vfio_pci_load_rom, \
# trace:vfio_rom_read, \
# trace:vfio_pci_size_rom, \
# trace:vfio_vga_write, \
# trace:vfio_vga_read, \
# trace:vfio_pci_read_config, \
# trace:vfio_pci_write_config, \
# trace:vfio_msi_setup, \
# trace:vfio_msix_early_setup, \
# trace:vfio_check_pcie_flr, \
# trace:vfio_check_pm_reset, \
# trace:vfio_check_af_flr, \
# trace:vfio_pci_hot_reset, \
# trace:vfio_pci_hot_reset_has_dep_devices, \
# trace:vfio_pci_hot_reset_dep_devices, \
# trace:vfio_pci_hot_reset_result, \
# trace:vfio_populate_device_config, \
# trace:vfio_populate_device_get_irq_info_failure, \
# trace:vfio_initfn, \
# trace:vfio_pci_reset, \
# trace:vfio_pci_reset_flr, \
# trace:vfio_pci_reset_pm, \
# trace:vfio_pci_emulated_vendor_id, \
# trace:vfio_pci_emulated_device_id, \
# trace:vfio_pci_emulated_sub_vendor_id, \
# trace:vfio_pci_emulated_sub_device_id, \
# trace:vfio_quirk_rom_blacklisted, \
# trace:vfio_quirk_generic_window_address_write, \
# trace:vfio_quirk_generic_window_data_read, \
# trace:vfio_quirk_generic_window_data_write, \
# trace:vfio_quirk_generic_mirror_read, \
# trace:vfio_quirk_generic_mirror_write, \
# trace:vfio_quirk_ati_3c3_read, \
# trace:vfio_quirk_ati_3c3_probe, \
# trace:vfio_quirk_ati_bar4_probe, \
# trace:vfio_quirk_ati_bar2_probe, \
# trace:vfio_quirk_nvidia_3d0_state, \
# trace:vfio_quirk_nvidia_3d0_read, \
# trace:vfio_quirk_nvidia_3d0_write, \
# trace:vfio_quirk_nvidia_3d0_probe, \
# trace:vfio_quirk_nvidia_bar5_state, \
# trace:vfio_quirk_nvidia_bar5_probe, \
# trace:vfio_quirk_nvidia_bar0_msi_ack, \
# trace:vfio_quirk_nvidia_bar0_probe, \
# trace:vfio_quirk_rtl8168_fake_latch, \
# trace:vfio_quirk_rtl8168_msix_write, \
# trace:vfio_quirk_rtl8168_msix_read, \
# trace:vfio_quirk_rtl8168_probe, \
# trace:vfio_quirk_ati_bonaire_reset_skipped, \
# trace:vfio_quirk_ati_bonaire_reset_no_smc, \
# trace:vfio_quirk_ati_bonaire_reset_timeout, \
# trace:vfio_quirk_ati_bonaire_reset_done, \
# trace:vfio_quirk_ati_bonaire_reset, \
# trace:vfio_region_write, \
# trace:vfio_region_read, \
# trace:vfio_iommu_map_notify, \
# trace:vfio_listener_region_add_skip, \
# trace:vfio_listener_region_add_iommu, \
# trace:vfio_listener_region_add_ram, \
# trace:vfio_listener_region_del_skip, \
# trace:vfio_listener_region_del, \
# trace:vfio_disconnect_container, \
# trace:vfio_put_group, \
# trace:vfio_get_device, \
# trace:vfio_put_base_device, \
# trace:vfio_region_setup, \
# trace:vfio_region_mmap_fault, \
# trace:vfio_region_mmap, \
# trace:vfio_region_exit, \
# trace:vfio_region_finalize, \
# trace:vfio_region_mmaps_set_enabled, \
# trace:vfio_platform_base_device_init, \
# trace:vfio_platform_realize, \
# trace:vfio_platform_eoi, \
# trace:vfio_platform_intp_mmap_enable, \
# trace:vfio_platform_intp_interrupt, \
# trace:vfio_platform_intp_inject_pending_lockheld, \
# trace:vfio_platform_populate_interrupts, \
# trace:vfio_intp_interrupt_set_pending, \
# trace:vfio_platform_start_level_irqfd_injection, \
# trace:vfio_platform_start_edge_irqfd_injection, \
# trace:mhp_acpi_invalid_slot_selected, \
# trace:mhp_acpi_ejecting_invalid_slot, \
# trace:mhp_acpi_read_addr_lo, \
# trace:mhp_acpi_read_addr_hi, \
# trace:mhp_acpi_read_size_lo, \
# trace:mhp_acpi_read_size_hi, \
# trace:mhp_acpi_read_pxm, \
# trace:mhp_acpi_read_flags, \
# trace:mhp_acpi_write_slot, \
# trace:mhp_acpi_write_ost_ev, \
# trace:mhp_acpi_write_ost_status, \
# trace:mhp_acpi_clear_insert_evt, \
# trace:mhp_acpi_clear_remove_evt, \
# trace:mhp_acpi_pc_dimm_deleted, \
# trace:mhp_acpi_pc_dimm_delete_failed, \
# trace:mhp_pc_dimm_assigned_slot, \
# trace:mhp_pc_dimm_assigned_address, \
# trace:kvm_enable_cmma, \
# trace:kvm_clear_cmma, \
# trace:kvm_failed_cpu_state_set, \
# trace:kvm_sigp_finished, \
# trace:i8257_unregistered_dma, \
# trace:cpu_set_state, \
# trace:cpu_halt, \
# trace:cpu_unhalt, \
# trace:virt_acpi_setup, \
# trace:alpha_pci_iack_write, \
# trace:alsa_revents, \
# trace:alsa_pollout, \
# trace:alsa_set_handler, \
# trace:alsa_wrote_zero, \
# trace:alsa_read_zero, \
# trace:alsa_xrun_out, \
# trace:alsa_xrun_in, \
# trace:alsa_resume_out, \
# trace:alsa_resume_in, \
# trace:alsa_no_frames, \
# trace:oss_version, \
# trace:oss_invalid_available_size, \
# trace:qcrypto_tls_creds_load_dh, \
# trace:qcrypto_tls_creds_get_path, \
# trace:qcrypto_tls_creds_anon_load, \
# trace:qcrypto_tls_creds_x509_load, \
# trace:qcrypto_tls_creds_x509_check_basic_constraints, \
# trace:qcrypto_tls_creds_x509_check_key_usage, \
# trace:qcrypto_tls_creds_x509_check_key_purpose, \
# trace:qcrypto_tls_creds_x509_load_cert, \
# trace:qcrypto_tls_creds_x509_load_cert_list, \
# trace:qcrypto_tls_session_new, \
# trace:vhost_user_event, \
# trace:user_setup_frame, \
# trace:user_setup_rt_frame, \
# trace:user_do_rt_sigreturn, \
# trace:user_do_sigreturn, \
# trace:user_force_sig, \
# trace:user_handle_signal, \
# trace:user_host_signal, \
# trace:user_queue_signal, \
# trace:user_s390x_restore_sigregs, \
# trace:qio_task_new, \
# trace:qio_task_complete, \
# trace:qio_task_abort, \
# trace:qio_task_thread_start, \
# trace:qio_task_thread_run, \
# trace:qio_task_thread_exit, \
# trace:qio_task_thread_result, \
# trace:qio_channel_socket_new, \
# trace:qio_channel_socket_new_fd, \
# trace:qio_channel_socket_connect_sync, \
# trace:qio_channel_socket_connect_async, \
# trace:qio_channel_socket_connect_fail, \
# trace:qio_channel_socket_connect_complete, \
# trace:qio_channel_socket_listen_sync, \
# trace:qio_channel_socket_listen_async, \
# trace:qio_channel_socket_listen_fail, \
# trace:qio_channel_socket_listen_complete, \
# trace:qio_channel_socket_dgram_sync, \
# trace:qio_channel_socket_dgram_async, \
# trace:qio_channel_socket_dgram_fail, \
# trace:qio_channel_socket_dgram_complete, \
# trace:qio_channel_socket_accept, \
# trace:qio_channel_socket_accept_fail, \
# trace:qio_channel_socket_accept_complete, \
# trace:qio_channel_file_new_fd, \
# trace:qio_channel_file_new_path, \
# trace:qio_channel_tls_new_client, \
# trace:qio_channel_tls_new_server, \
# trace:qio_channel_tls_handshake_start, \
# trace:qio_channel_tls_handshake_pending, \
# trace:qio_channel_tls_handshake_fail, \
# trace:qio_channel_tls_handshake_complete, \
# trace:qio_channel_tls_credentials_allow, \
# trace:qio_channel_tls_credentials_deny, \
# trace:qio_channel_websock_new_server, \
# trace:qio_channel_websock_handshake_start, \
# trace:qio_channel_websock_handshake_pending, \
# trace:qio_channel_websock_handshake_reply, \
# trace:qio_channel_websock_handshake_fail, \
# trace:qio_channel_websock_handshake_complete, \
# trace:qio_channel_command_new_pid, \
# trace:qio_channel_command_new_spawn, \
# trace:qio_channel_command_abort, \
# trace:qio_channel_command_wait, \
# trace:aspeed_timer_ctrl_enable, \
# trace:aspeed_timer_ctrl_external_clock, \
# trace:aspeed_timer_ctrl_overflow_interrupt, \
# trace:aspeed_timer_ctrl_pulse_enable, \
# trace:aspeed_timer_set_ctrl2, \
# trace:aspeed_timer_set_value, \
# trace:aspeed_timer_read, \
# trace:aspeed_vic_set_irq, \
# trace:aspeed_vic_update_fiq, \
# trace:aspeed_vic_update_irq, \
# trace:aspeed_vic_read, \
# trace:aspeed_vic_write



# test in debug mode
#  


# trace:qemu_memalign,qemu_memalign,qemu_anon_ram_alloc,ledma_memory_read,espdma_memory_read,espdma_memory_write,lm32_timer_memory_write,lm32_timer_memory_read,lm32_uart_memory_write,lm32_uart_memory_read,milkymist_ac97_memory_read,milkymist_ac97_memory_write,milkymist_tmu2_memory_read,milkymist_tmu2_memory_write,milkymist_uart_memory_read,milkymist_uart_memory_write,milkymist_vgafb_memory_read,milkymist_vgafb_memory_write,memory_region_ops_read,memory_region_ops_write,memory_region_subpage_read,memory_region_subpage_write,memory_region_tb_read,memory_region_tb_write,milkymist_sysctl_memory_read,milkymist_sysctl_memory_write,milkymist_softusb_memory_read,milkymist_softusb_memory_write,milkymist_hpdmc_memory_read,milkymist_hpdmc_memory_write,milkymist_memcard_memory_read,milkymist_memcard_memory_write,milkymist_minimac2_memory_read,milkymist_minimac2_memory_write,milkymist_minimac2_mdio_write,milkymist_minimac2_mdio_read,milkymist_pfpu_memory_read,milkymist_pfpu_memory_write,ledma_memory_write

qemu-system-x86_64    -d out_asm,in_asm,op,op_opt,int,exec,cpu,mmu,pcall,cpu_reset,unimp,guest_errors,page,nochain -device pc-testdev   -device isa-debug-exit,iobase=0xf4,iosize=0x4   -serial stdio   -device pci-testdev   -kernel ./x86/realmode.flat

#
#qemu-system-x86_64  -d cpu  -device pc-testdev -device isa-debug-exit, iobase=0xf4, \ iosize=0x4  -serial stdio -device pci-testdev -kernel ./x86/msr.flat 

# 
